spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
socket-server.port=8085
socket-server.host=0.0.0.0


spring.main.allow-circular-references = true

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/iot_gateway?createDatabaseIfNotExist=true}
spring.datasource.username=mysql
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Enable Swagger UI
springfox.documentation.swagger-ui.enabled=true

spring.security.user.name=admin
spring.security.user.password=${DEMO_USER_PASSWORD}


